defmodule AshFoundry.Plan do
  @moduledoc "Validated, deterministic input to AshFoundry generation."

  alias AshFoundry.Selection

  @enforce_keys [
    :app,
    :module,
    :recipe,
    :auth,
    :registration,
    :tenancy,
    :deploy,
    :google_hosted_domain,
    :organization_creation,
    :session_absolute_minutes,
    :session_idle_minutes
  ]
  defstruct @enforce_keys

  @type recipe :: Selection.recipe()
  @type auth_method :: Selection.auth_method()
  @type registration :: Selection.registration()
  @type tenancy :: Selection.tenancy()
  @type deployment :: Selection.deployment()
  @type organization_creation :: Selection.organization_creation()
  @type t :: %__MODULE__{
          app: String.t(),
          module: String.t(),
          recipe: recipe(),
          auth: [auth_method()],
          registration: registration(),
          tenancy: tenancy(),
          deploy: deployment(),
          google_hosted_domain: boolean(),
          organization_creation: organization_creation(),
          session_absolute_minutes: pos_integer(),
          session_idle_minutes: pos_integer()
        }

  @doc "Builds and validates a normalized plan from CLI-style options."
  @spec build(String.t(), keyword()) :: {:ok, t()} | {:error, String.t()}
  def build(app, options) when is_binary(app) and is_list(options) do
    with :ok <- validate_app(app),
         {:ok, recipe} <- Selection.enum(options[:recipe], Selection.recipes(), "recipe"),
         defaults = Selection.defaults(recipe),
         {:ok, auth} <- Selection.auth(options[:auth], defaults, recipe),
         {:ok, registration} <-
           Selection.selected(options, defaults, recipe, :registration, Selection.registrations()),
         {:ok, tenancy} <-
           Selection.selected(options, defaults, recipe, :tenancy, Selection.tenancies()),
         {:ok, deploy} <- Selection.enum(options[:deploy], Selection.deployments(), "deploy"),
         :ok <- Selection.validate_combination(auth, registration, tenancy, options) do
      module = options[:ash_foundry_module] || options[:module] || Macro.camelize(app)
      {absolute, idle} = Selection.session_minutes(defaults)

      {:ok,
       %__MODULE__{
         app: app,
         module: module,
         recipe: recipe,
         auth: auth,
         registration: registration,
         tenancy: tenancy,
         deploy: deploy,
         google_hosted_domain: Selection.hosted_domain?(options, defaults, auth),
         organization_creation: Selection.organization_creation(recipe, tenancy),
         session_absolute_minutes: absolute,
         session_idle_minutes: idle
       }}
    end
  end

  @doc "Builds a plan, raising a Mix error when input is invalid."
  @spec build!(String.t(), keyword()) :: t()
  def build!(app, options) do
    case build(app, options) do
      {:ok, plan} -> plan
      {:error, message} -> Mix.raise(message)
    end
  end

  @doc "True when the CLI selection will generate authentication."
  @spec auth_enabled?(keyword()) :: boolean()
  def auth_enabled?(options), do: Selection.auth_enabled?(options)

  @doc "Returns the complete deterministic CLI arguments for a plan."
  @spec cli_args(t()) :: [String.t()]
  def cli_args(plan) do
    [
      plan.app,
      "--module",
      plan.module,
      "--recipe",
      Atom.to_string(plan.recipe),
      "--auth",
      auth_string(plan.auth),
      "--registration",
      Selection.dashed(plan.registration),
      "--tenancy",
      Atom.to_string(plan.tenancy),
      "--deploy",
      Atom.to_string(plan.deploy),
      if(plan.google_hosted_domain,
        do: "--google-hosted-domain",
        else: "--no-google-hosted-domain"
      )
    ]
  end

  @doc "Serializes the stable, secret-free provenance written to generated apps."
  @spec provenance(t()) :: String.t()
  def provenance(plan) do
    fields = [
      ash_foundry: AshFoundry.version(),
      module: plan.module,
      recipe: plan.recipe,
      auth: plan.auth,
      registration: plan.registration,
      tenancy: plan.tenancy,
      deploy: plan.deploy,
      google_hosted_domain: plan.google_hosted_domain,
      organization_creation: plan.organization_creation,
      session_absolute_minutes: plan.session_absolute_minutes,
      session_idle_minutes: plan.session_idle_minutes
    ]

    "# Generated by AshFoundry. This file contains no secrets.\n" <>
      inspect(fields, pretty: true, width: 98, limit: :infinity) <> "\n"
  end

  defp validate_app(app) do
    if Regex.match?(~r/^[a-z][a-z0-9_]*$/, app) and not String.ends_with?(app, "_web") do
      :ok
    else
      {:error, "APP_NAME must be a snake_case Elixir application name and must not end in _web"}
    end
  end

  defp auth_string([]), do: "none"
  defp auth_string(methods), do: Enum.map_join(methods, ",", &Selection.dashed/1)
end
